---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7

suites:
  - name: all
    run_list:
      - role[app_server]
      - recipe[task1_jboss::deploy]
