---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-7

suites:
  - name: all
    run_list:
      - recipe[task1_apache::default]
      - recipe[task1_community::default]
      - recipe[task1_jboss::default]
